#!/bin/bash
case $BLOCK_BUTTON in
    1) notify-send "内存消耗" "$(ps axch -o cmd:15,%mem --sort=-%mem | head)" ;;
    3) dwmblocktools-exec 'st -e htop' ;;
    6) "code" "$0";;
esac

echo $(free --mebi | sed -n '2{p;q}' | awk '{printf (" %2.2fGi/%2.2fGi\n", ( $3 / 1024), ($2 / 1024))}')