#!/bin/bash
case $BLOCK_BUTTON in
    1) notify-send "月份信息" "$(cal --color=always | sed "s/..7m/<b><span color=\"red\">/;s/..27m/<\/span><\/b>/")" && notify-send "日程" "$(calcurse -D ~/.config/calcurse -d3)" ;;
    3) dwmblocktools-exec 'st -e calcurse' ;;
    6) "code" "$0";;
esac

clock=$(date '+%H')
if (( clock < 8 )); then
    sign="晚安"
elif (( clock < 12 )); then
    sign="早上好"
elif (( clock < 14 )); then
    sign="中午好"
elif (( clock < 18 )); then
    sign="下午好"
else
    sign="晚上好"
fi

echo " $sign $(date +"%R:%S")"